[package]
org = "danielfavoreto"
name = "kafka_nossis_producer"
version = "0.1.0"
distribution = "2201.13.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.2"

[build-options]
observabilityIncluded = true
